<?php
// $Id: thisdayinhistory.module,v 1.2.2.4 2009/09/05 21:58:36 dmcgladdery Exp $

/**
 * @file
 * Main module file for This Day in History module.
 */

/**
 * Implementation of hook_help().
 */
function thisdayinhistory_help($path, $arg) {
  switch ($path) {
    case 'admin/help#thisdayinhistory':
      // This description shows up when users click "create content."
      $help_text = '<p>The <em>This Day in History</em> module allows users with the appropriate permissions to enter historical events. The historical events can be displayed in any number of Administrator defined blocks. Blocks can be configured to display historical events based on different criteria, such as taxonomy terms.</p>';
      return t($help_text);
      break;
  }
}


/**
 * Implementation of hook_node_info().
 */
function thisdayinhistory_node_info() {
  return array(
    'thisdayinhistory' => array(
      'name' => t('Historical event'),
      'base' => 'thisdayinhistory',
      'description' => t("An interesting or historical event from the past."),
      'has_title' => TRUE,
    )
  );
}


/**
 * Implementation of hook_perm().
 */
function thisdayinhistory_permission() {
  return array(
    'administer this day in history' => array(
      'title' => t('Administer This Day in History'),
      'description' => t('Perform administration tasks for TDIH module.'),
    ),
    'create historical events' => array(
      'title' => t('Create historical events'),
      'description' => t('Allows creation of TDIH content/nodes.'),
    ),
    'edit own historical events' => array(
      'title' => t('Edit own historical events'),
      'description' => t('Allows editing of owned TDHI nodes.'),
    ),
    'promote historical events to block' => array(
      'title' => t('Promote historical events to block'),
      'description' => t('Allows promoting own node to the frontpage block.'),
    )
  );
}


/**
 * Implementation of hook_access().
 */
function thisdayinhistory_node_access($node, $op, $account) {
  // Admins can do anything
  if (user_access('administer this day in history', $account)) {
    return NODE_ACCESS_ALLOW;
  }

  if ($op == 'create' && user_access('create historical events', $account)) {
    return NODE_ACCESS_ALLOW;
  }

  if ($op == 'update' || $op == 'delete') {
    if (user_access('edit own historical events', $account) && ($account->uid == $node->uid)) {
      return NODE_ACCESS_ALLOW;
    }
  }
}


/**
 * Implementation of hook_menu().
 */
function thisdayinhistory_menu() {
  $items = array();

  $items['admin/config/content/thisdayinhistory'] = array(
    'title' => 'This Day in History',
    'description' => 'Create and configure This Day in History blocks and configure options.',
    'access callback' => 'user_access',
    'access arguments' => array('administer this day in history'),
    'page callback' => 'thisdayinhistory_admin_overview',
    //'page arguments' => array('_thisdayinhistory_admin_settings'),
    'file' => 'thisdayinhistory.admin.inc',
    'type' => MENU_NORMAL_ITEM,
  );
  $items['admin/config/content/thisdayinhistory/overview'] = array(
    'title' => 'Overview',
    'description' => 'Create and configure This Day in History blocks and configure options.',
    'access callback' => 'user_access',
    'access arguments' => array('administer this day in history'),
    'file' => 'thisdayinhistory.admin.inc',
    'type' => MENU_DEFAULT_LOCAL_TASK,
    'weight' => -2
  );
  $items['admin/config/content/thisdayinhistory/blocks'] = array(
    'title' => 'Configure blocks',
    'description' => 'Configure blocks.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('thisdayinhistory_blocks_configure'),
    'access callback' => 'user_access',
    'access arguments' => array('administer this day in history'),
    'file' => 'thisdayinhistory.admin.inc',
    'type' => MENU_LOCAL_TASK,
    'weight' => -1
  );
  $items['admin/config/content/thisdayinhistory/blocks/delete'] = array(
    'title' => 'Delete TDIH block',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('thisdayinhistory_block_delete_confirmation'),
    'access callback' => 'user_access',
    'access arguments' => array('administer this day in history'),
    'file' => 'thisdayinhistory.admin.inc',
    'type' => MENU_CALLBACK
  );

  return $items;
}


/**
 * Implementation of hook_form().
 */
function thisdayinhistory_form($node, $form_state) {
  $type = node_type_get_type($node);
  drupal_add_css(drupal_get_path('module', 'thisdayinhistory') .'/thisdayinhistory.css');

  $form['title'] = array(
    '#type' => 'textfield',
    '#title' => check_plain($type->title_label),
    '#required' => TRUE,
    '#default_value' => $node->title,
    '#weight' => -9
  );

  // Now we define the form elements specific to our node type.
  $form['tdih_date'] = array(
    '#attributes'   => array('class' => array('tdih-date')),
    '#weight'       => -5
  );
  $form['tdih_date']['year'] = array(
    '#type' => 'textfield',
    '#title' => t('Year'),
    '#required' => TRUE,
    '#default_value' => !empty($node->year) ? $node->year : '',
    '#size' => 4,
    '#maxlength' => 4,
    '#field_suffix' => ' - ',
    '#attributes'   => array('class' => array('tdih-datefield')),
    '#prefix' => '<div class="tdih-date form-item"><label>Date:</label>',
  );
  $form['tdih_date']['month'] = array(
    '#type' => 'textfield',
    '#title' => t('Month'),
    '#required' => TRUE,
    '#default_value' => !empty($node->month) ? $node->month : '',
    '#size' => 4,
    '#maxlength' => 2,
    '#field_suffix' => ' - ',
  );
  $form['tdih_date']['day'] = array(
    '#type' => 'textfield',
    '#title' => t('Day'),
    '#required' => TRUE,
    '#default_value' => !empty($node->day) ? $node->day : '',
    '#size' => 4,
    '#maxlength' => 2,
    '#suffix' => '</div><div style="clear:both;"></div>'
  );

  if (user_access('promote historical events to block')) {
    $form['blockdisplay'] = array(
      '#type' => 'checkbox',
      '#title' => t('Display in TDiH blocks'),
      '#default_value' => (isset($node->blockdisplay) ? $node->blockdisplay : 1)
    );
  }

  return $form;
}


/**
 * Implementation of hook_validate().
 */
function thisdayinhistory_validate($node, &$form) {
  $texterror = FALSE;
  if (!is_numeric($node->year)) {
    form_set_error('year', t('Year value must be entered as a integer'));
    $texterror = TRUE;
  }
  if (!is_numeric($node->month)) {
    form_set_error('month', t('Month value must be entered as a integer'));
    $texterror = TRUE;
  }
  if (!is_numeric($node->day)) {
    form_set_error('day', t('Day value must be entered as a integer'));
    $texterror = TRUE;
  }
  if ($texterror) return;

  if ($node->month < 1) {
    form_set_error('month', t('Month value can not be set less than 1'));
    return;
  }
  if ($node->month > 12) {
    form_set_error('month', t('Month value can not be set larger than 12'));
    return;
  }

  $days_in_month = array(0, 31, 29, 31, 30, 31, 30, 31, 31, 30, 31, 30, 31);
  if ($node->day < 1) {
    form_set_error('day', t('Day value can not be set less than 1'));
    return;
  }
  if ($node->day > $days_in_month[(int)$node->month]) {
    form_set_error('day', t('Day value is too large'));
    return;
  }
}


/**
 * Implementation of hook_insert().
 */
function thisdayinhistory_insert($node) {
  $isodate = $node->year .'-'. $node->month .'-'. $node->day;
  db_query("INSERT INTO {thisdayinhistory}
          (vid, nid, isodate, blockdisplay)
          VALUES (:vid, :nid, :isodate, :blockdisplay)", array(
          ':vid' => $node->vid, ':nid' => $node->nid, ':isodate' => $isodate, ':blockdisplay' => $node->blockdisplay));
}


/**
 * Implementation of hook_update().
 */
function thisdayinhistory_update($node) {
  // if this is a new node or we're adding a new revision,
  if ($node->revision) {
    thisdayinhistory_insert($node);
  } else {
    $isodate = $node->year .'-'. $node->month .'-'. $node->day;
    db_query("UPDATE {thisdayinhistory}
            SET isodate = :isodate, blockdisplay = :blockdisplay WHERE nid = :nid",
            array(':isodate' => $isodate, ':blockdisplay' => $node->blockdisplay, ':nid' => $node->nid));
  }
}


/**
 * Implementation of hook_delete().
 */
function thisdayinhistory_delete($node) {
  // When a node is deleted, we need to remove all related records from out table.
  // Notice that we're matching all revision, by using the node's nid.
  db_query('DELETE FROM {thisdayinhistory} WHERE nid = :nid', array(':nid' => $node->nid));
}


/**
 * Implementation of hook_load().
 */
function thisdayinhistory_load($nodes) {
  $result = db_query('SELECT nid, DATE(tdih.isodate) as isodate, tdih.blockdisplay FROM {thisdayinhistory} tdih WHERE nid IN (:nids)', array(':nids' => array_keys($nodes)));
  foreach($result as $record) {
    $nodes[$record->nid]->isodate = $record->isodate;
    if ($record->isodate) {
      list($year, $month, $day) = explode('-', $record->isodate);
      $nodes[$record->nid]->year   = $year;
      $nodes[$record->nid]->month  = $month;
      $nodes[$record->nid]->day    = $day;
    }
  }
}


/**
 * Implementation of hook_view().
 */
function thisdayinhistory_view($node, $view_mode) {
  node_object_prepare($node);
  if (!$node->isodate) $node->isodate = $node->year .'-'. $node->month .'-'. $node->day;
  $node->content['thisdayinhistory'] = array(
    '#markup' => theme('thisdayinhistory_node_field', array('node' => $node)),
    '#weight' => -1,
  );

  return $node;
}


/**
 * Implementation of hook_block_info().
 */
function thisdayinhistory_block_info() {
  $blocks = array();
  $block_list = db_query('SELECT tdihb.bid, tdihb.name FROM {thisdayinhistory_blocks} tdihb');
  foreach ($block_list as $block) {
    $blocks[$block->bid] = array('info' => t('TDiH') .': '. $block->name);
  }
  return $blocks;
}

/**
 * Implementation of hook_block_configure().
 */
function thisdayinhistory_block_configure($delta = '') {
  $result = db_query("SELECT tdihb.* FROM {thisdayinhistory_blocks} tdihb WHERE bid = :delta", array(':delta' => $delta));
  $block = $result->fetch();

  $block->uid_filter = explode(',', $block->uid_filter);
  $block->tid_filter = explode(',', $block->tid_filter);
  $block->rid_filter = explode(',', $block->rid_filter);

  // get roles
  $roles = user_roles(FALSE, 'create historical events');
  foreach (user_roles(FALSE, 'edit own historical events') as $rid => $role) {
    $roles[$rid] = $role;
  }
  foreach (user_roles(FALSE, 'administer this day in history') as $rid => $role) {
    $roles[$rid] = $role;
  }

  // Get users
  $users = array();
  if (isset($roles[DRUPAL_ANONYMOUS_RID])) {
    $users[0] = variable_get('anonymous', t('Anonymous'));
  }
  $result = db_query(
    "SELECT DISTINCT u.uid, u.name
        FROM {users} u
        LEFT JOIN {users_roles} ur ON ur.uid = u.uid
        WHERE u.uid = 1 OR ur.rid IN (:roles)",
    array(':roles' => implode(',', (count($roles) ? array_keys($roles) : array(0))))
  );
  foreach ($result as $row) {
    $users[$row->uid] = ($row->uid ? $row->name : variable_get('anonymous', t('Anonymous')));
  }

  $form = array();

  if ($delta) {
    $form['bid'] = array(
      '#type' => 'value',
      '#value' => $delta
    );
  }

  $form['name'] = array(
    '#type' => 'textfield',
    '#title' => t('Name'),
    '#required' => TRUE,
    '#default_value' => $block->name,
    '#description' => t('Enter a unique name for this block. This will identify the block on the !block administration page and be used for the default block title.', array('!block administration page' => l(t('block administration page'), 'admin/build/block'), '%title' => '%title'))
  );
  $form['header']['header_field'] = array(
    '#type' => 'textarea',
    '#title' => t('Header'),
    '#default_value' => $block->header,
  );
  $form['block_type'] = array(
    '#type' => 'radios',
    '#title' => t('Type'),
    '#required' => TRUE,
    '#default_value' => (($block->block_type == 1) ? 1 : 0),
    '#options' => array(t('All'), t('Random'))
  );

  if (count($roles)) {
    $form['rid_filter'] = array(
      '#type' => 'select',
      '#title' => t('Role filter'),
      '#multiple' => TRUE,
      '#default_value' => $block->rid_filter,
      '#options' => $roles,
      '#description' => t('To restrict this block to display only quotes submitted by users in specific roles, select the roles here.')
    );
  }
  else {
    $form['rid_filter'] = array(
      '#type' => 'item',
      '#title' => t('Role filter'),
      '#description' => t('There are no roles configured with the %create historical events, %administer this day in history permissions, or %edit own historical events, so no roles are available. To filter by role, please assign this permission to at least one role on the !access control page.', array('%create historical events' => t('create historical events'), '%administer this day in history' => t('administer this day in history'), '%edit own historical events' => t('edit own historical events'), '!access control page' => l(t('access control page'), 'admin/user/access')))
    );
  }

  $form['uid_filter'] = array(
    '#type' => 'select',
    '#title' => t('User filter'),
    '#multiple' => TRUE,
    '#default_value' => $block->uid_filter,
    '#options' => $users,
    '#description' => t('To restrict this block to display only This Day in History events submitted by specific users, select the users here.')
  );

  if (function_exists('taxonomy_form_all')) {
    $form['tid_filter'] = array(
      '#type' => 'select',
      '#title' => t('Category filter'),
      '#multiple' => TRUE,
      '#default_value' => $block->tid_filter,
      '#options' => taxonomy_form_all(TRUE),
      '#description' => t('To restrict this block to display only This Day in History events in specific categories, select the categories here.')
    );
  }

  return $form;
}

/**
 * Implementation of hook_block_view().
 */
function thisdayinhistory_block_view($delta = '') {
  drupal_add_css(drupal_get_path('module', 'thisdayinhistory') .'/thisdayinhistory.css',
    array('group' => CSS_DEFAULT, 'every_page' => TRUE));
  return thisdayinhistory_get_block($delta);
}

/**
 * Implementation of hook_block_save().
 */
function thisdayinhistory_block_save($delta = '', $edit = array()) {
  $uids = implode(',', (array) $edit['uid_filter']);
  $rids = implode(',', (array) $edit['rid_filter']);
  //Hard coding header filter as filter_html because some sites have machine name while upgraded D6->D7 sites still have integers

  db_query(
    "UPDATE {thisdayinhistory_blocks}
        SET name = :name, block_type = :block, uid_filter = :uids, rid_filter = :rids, header = :hfield, header_format = :hfilter
        WHERE bid = :delta",
    array(':name' => $edit['name'], ':block' => (($edit['block_type'] == 1) ? 1 : 0), ':uids' => $uids,
      ':rids' => $rids, ':hfield' => $edit['header_field'], ':hfilter' => 2, ':delta' => $delta)
  );
}

/**
 * Returns a list of This Day in History nodes based on the option list passed to it.
 * The option list is designed to accept a Block array retrieved from the database.
 *
 * @param $options
 *   The array specifying options and filter criteria
 *
 * @return
 *   A list of nodes matching the specified options and criteria.
 */
function thisdayinhistory_get_events($options = array()) {
  // Default values
  $month      = format_date(time(), 'custom', 'n');
  $day        = format_date(time(), 'custom', 'j');
  $promote    = '1';
  $type       = 'all';

  $query = db_select('thisdayinhistory', 'tdih');
  $query->leftJoin('node', 'n', 'n.vid = tdih.vid');
  $query->fields('n', array('nid'));
  $query->addTag('node_access');

  // Evaluate $options
  foreach ($options as $name => $value) {
    switch ($name) {
      case 'uid_filter':
        if ($value) {
          $query->condition('n.uid', $value, 'IN');
        }
        break;
      case 'tid_filter':
        if ($value) {
          $query->innerJoin('term_node', 'tn', 'tn.nid = n.nid');
          $query->condition('tn.tid', $value, 'IN');
        }
        break;
      case 'rid_filter':
        if ($value) {
          $query->leftJoin('users_roles', 'ur', 'ur.uid = n.uid');
          $query->condition(db_or()->condition('ur.rid', $value, 'IN')->db_and()->condition(DRUPAL_ANONYMOUS_RID, $value, 'IN')->condition('n.uid', 0));
        }
        break;
      case 'promoted_only':
        $promote = ($value) ? 1 : 0;
        break;
      case 'month':
        $month = $value;
        break;
      case 'day':
        $day = $value;
        break;
      case 'block_type':
        switch ($value) {
          case 0:
            $type = 'all';
            break;
          case 1:
            $type = 'random';
            break;
        }
        break;
    }
  }

  $query->where("month(tdih.isodate)= :month", array(':month' => $month))
        ->where("dayofmonth(tdih.isodate) = :day", array(':day' => $day));
  $query->condition('n.status', 1)
        ->condition('n.type', 'thisdayinhistory')
        ->condition('tdih.blockdisplay', $promote);
  $query->orderBy('tdih.isodate');

  //$queryresult = db_query($query, array(':month' => $month, ':day' => $day));
  $queryresult = $query->execute();

  $nodelist = array();
  foreach ($queryresult as $entry) {
    $nodelist[] = $entry->nid;
  }

  if ($type == 'random') {
    $count = count($nodelist);
    if ($count > 0) {
      $randomnode = $nodelist[rand(0, $count - 1)];
      $nodelist = array($randomnode);
    }
  }

  $renderednodes = array();
  foreach ($nodelist as $node_id) {
    $renderednodes[] = node_load($node_id);
  }
  return $renderednodes;
}

function thisdayinhistory_get_block($delta) {
  $result = db_query('SELECT tdihb.* FROM {thisdayinhistory_blocks} tdihb WHERE tdihb.bid = :delta', array(':delta' => $delta));
  $block = $result->fetchAssoc();
  if (!$block) {
    return NULL;
  }
  $block['header'] = check_markup($block['header'], $block['header_format'], FALSE);

  $eventnodes = thisdayinhistory_get_events($block);

  if (count($eventnodes) == 0) {
    return NULL;
  }
  else {
    return array(
      'subject' => $block['name'],
      'content' => theme('thisdayinhistory_block_content', array('block' => $block, 'node_list' => $eventnodes))
    );
  }
}


/**
 *
 * Theme Functions
 *
 */

/**
 * Implementation of hook_theme().
 */
function thisdayinhistory_theme() {
  return array(
    'thisdayinhistory_blocks_configure' => array(
      'variables' => array('form' => NULL),
      'render element' => 'form',
    ),
    'thisdayinhistory_node_field' => array(
      'file' => 'thisdayinhistory.module',
      'variables' => array(
        'node' => NULL,
      ),
    ),
    'thisdayinhistory_block_content' => array(
      'template'  => 'thisdayinhistory-block-content',
      'path'      => drupal_get_path('module', 'thisdayinhistory') .'/theme',
      'variables' => array(
        'block' => NULL,
        'node_list' => NULL,
      ),
    ),
  );
}


/**
 * Default theme function for TDiH date field displayed with node
 */
function theme_thisdayinhistory_node_field($variables) {
  $node = $variables['node'];
  $output = '<div class="thisdayinhistory-date">';
  $output .= t('Date: !isodate', array('!isodate' => check_plain($node->isodate)));
  $output .= '</div>';
  return $output;
}


/**
 *
 * Import Node Module Hooks
 *
 */

/**
 * Implementation of Node Import's hook_node_import_fields().
 */
function thisdayinhistory_node_import_fields($type) {
  if ($type == 'node:thisdayinhistory') {
    return array(
      'iso_date' => array(
        'title'         => t('TDiH Event Date, formatted: yyyy-mm-dd'),
        'is_mappable'   => TRUE,
        'map_required'  => FALSE,
      ),
      'european_date' => array(
        'title'         => t('TDiH Event Date, formatted: dd/mm/yyyy'),
        'is_mappable'   => TRUE,
        'map_required'  => FALSE,
      ),
      'american_date' => array(
        'title'         => t('TDiH Event Date, formatted: mm/dd/yyyy'),
        'is_mappable'   => TRUE,
        'map_required'  => FALSE,
      ),
      'text_date' => array(
        'title'         => t('TDiH Event Date, formatted: mmm d, yyyy'),
        'is_mappable'   => TRUE,
        'map_required'  => FALSE,
      ),
      'blockdisplay' => array(
        'title'         => t('TDiH: Display in Block'),
        'is_mappable'   => TRUE,
        'map_required'  => FALSE,
      ),
    );
  }
}


/**
 * Implementation of Node Import's hook_node_import_values_alter().
 */
function thisdayinhistory_node_import_values_alter(&$values, $type, $options, $preview) {
  if ($values['iso_date']) {
    $dateparts = explode('-', check_plain($values['iso_date']));
    $values['year']   = $dateparts[0];
    $values['month']  = $dateparts[1];
    $values['day']    = $dateparts[2];
  }
  else if ($values['text_date']) {
    $monthmap = array(t('jan') => 1, t('feb') => 2, t('mar') => 3, t('apr') => 4, t('may') => 5, t('jun') => 6,
                      t('jul') => 7, t('aug') => 8, t('sep') => 9, t('oct') => 10, t('nov') => 11, t('dec') => 12 );
    $dateparts = explode(' ', check_plain($values['text_date']));
    $values['year']   = $dateparts[2];
    $values['month']  = $monthmap[strtolower($dateparts[0])];
    $values['day']    = str_replace(',', '', $dateparts[1]);
  }
  else if ($values['european_date']) {
    $dateparts = explode('/', check_plain($values['european_date']));
    $values['year']   = $dateparts[2];
    $values['month']  = $dateparts[1];
    $values['day']    = $dateparts[0];
  }
  else if ($values['american_date']) {
    $dateparts = explode('/', check_plain($values['american_date']));
    $values['year']   = $dateparts[2];
    $values['month']  = $dateparts[0];
    $values['day']    = $dateparts[1];
  }
  $values['isodate'] = $node->year .'-'. $node->month .'-'. $node->day;

  if ($values['blockdisplay'] == NULL) {
    $values['blockdisplay'] = 1;
  }
}

/**
 * Implementation of Node Import's hook_node_import_fields_alter().
 */
function thisdayinhistory_node_import_fields_alter(&$fields, $type) {
  $fields['body']['title'] = 'Event Description';
}
